config/routes.rb
Rails.application.routes.draw do

  get '/' => 'venues#index'
  
  devise_for :users

  get 'venues/save_query' => 'venues#save_query'

  resources :venues
  
  post 'venues/:id/rate' => 'venues#rate'

  get '/ratings/:id' => 'venues#rating'

  get '/welcome' => 'welcome#index'

  get '/my_ratings' => 'my_ratings#index'

  get "/about" => 'about#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :venue
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google]

  has_many :ratings
  
end

app/models/venue.rb
class Venue < ApplicationRecord

  has_many :ratings

  def full_address
    [self.address, self.city, self.state, self.country].compact.join(', ')
  end

  def update_ratings
    tags = %w{service price comfort noise overall}
    count = 0
    tags.each { |tag| self.send("#{tag}_rating=", 0)}
    self.ratings.each do |rating|
      tags.each { |tag| self.send("#{tag}_rating=", self.send("#{tag}_rating") + rating.send("#{tag}_rating"))  }
      count += 1
    end
    if count > 0
      tags.each { |tag| self.send("#{tag}_rating=", self.send("#{tag}_rating").to_f / count) }
    end
    self.rating_count = count
    self.save
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout 'application'

end

app/controllers/my_ratings_controller.rb
class MyRatingsController < ApplicationController

  before_action :authenticate_user!

  def index

    @ratings = current_user.ratings.order('updated_at desc')
    
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  
  before_action :authenticate_user!

  before_action :set_venue, only: [:show, :edit, :update, :destroy, :rate]

  # GET /venues
  def index
    @can_search = true
    @venues = Venue.all.limit(20)
    if cookies[:distance] && cookies[:distance] != 'Todos'
      @filtered = true
    end    
    if cookies[:venue_type] && cookies[:venue_type] != 'Todos'
      @filtered = true
      @venues = @venues.where(venue_type: cookies[:venue_type])
    end
    if cookies[:price_rating] && cookies[:price_rating] != 'Todos'
      @filtered = true
      @venues = @venues.where('price_rating > 0 and price_rating <= ?', cookies[:price_rating])
    end
    unless cookies[:q].blank?
      @filtered = true
      q = "%#{cookies[:q]}%"
      @venues = @venues.where("city like ? or state like ? or country like ?", q, q, q)
    end
  end

  # GET /venues/1
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue, notice: 'Obrigado por compartilhar mais um local conosco!.'
    else
      render :new
    end
  end

  # PATCH/PUT /venues/1
  def update
    if @venue.update(venue_params)
      redirect_to venues_url, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /venues/1
  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  #POST
  def rate
    @rating = Rating.new(rating_params)
    @rating.venue_id = params[:id]
    @rating.user = current_user
    if @rating.save
      @venue.update_ratings
      redirect_to venues_url, notice: "Obrigado por sua contribuição!"
    end
  end

  #POST
  def rating
    @rating = Rating.find(params[:id])
    @venue = @rating.venue

    render 'show'
  end

  #GET
  def save_query
    cookies[:q] = params[:q]
    cookies[:price_rating] = params[:price_rating]
    cookies[:venue_type] = params[:venue_type]
    cookies[:distance] = params[:distance]
    redirect_to venues_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def venue_params
      params.require(:venue).permit(:venue_name, :venue_type, :address, :city, :state, :country, :network_name, :network_is_free, :network_password)
    end

    def rating_params
      params.require(:rating).permit(:foods, :drinks, :service_rating, :price_rating, :comfort_rating, :noise_rating, :overall_rating)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_evaluation(value)
    html = ''
    (1..5).each do |i|
      if (value >= i)
        html += "<i class='fa fa-star'></i>"
      else
        html += "<i class='fa fa-star-o'></i>"
      end
    end
    html.html_safe
  end

  def input_evaluation(element)
    html = "<input type='hidden' name='#{element}' value='0'>"
    (1..5).each do |i|
      html += "<i class='fa fa-star-o rating-star' data-element='#{element}' data-value='#{i}'></i>"
    end
    html.html_safe
  end

end

app/helpers/my_ratings_helper.rb
module MyRatingsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="card">
  <div class="card-body">
    <p>
      Essa aplicação foi desenvolvida para o processo de seleção da Vibbra!  
    </p>
    <p>
      Seguindo a especificação do Teste Técnico foram desenvolvidas as seguintes atividades:

      <ul>
        <li>Cadastro/Login</li>
        <li>Minhas avaliações</li>
        <li>Listagem de estabelecimentos</li>
        <li>Visualização de estabelecimentos</li>
        <li>Cadastro de avaliação</li>
      </ul>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tem Wifi?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="/css/wifi.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <script src="/js/jquery-3.4.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
  </head>


  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

  <header class="masthead">
    <div class="inner">
      <h3 class="masthead-brand">Tem Wifi?</h3>
      <nav class="nav nav-masthead justify-content-center">
        <% unless current_user %>
        <a class="nav-link<%= " active" if request.path.to_s == "/users/sign_in"%>" href="/users/sign_in">Entrar</a>
        <% end %>
        <% if current_user %>
        <% if @can_search %>
        <a href="#" id="btn-search-open" class="btn btn-secondary mr-4"><i class="fa fa-search"></i></a>
        <% end %>
        <a class="nav-link<%= " active" if request.path.to_s == "/venues"%>" href="/venues">Estabelecimentos</a>
        <a class="nav-link<%= " active" if request.path.to_s == "/my_ratings"%>" href="/my_ratings">Minhas avaliações</a>
        <% end %>
        <a class="nav-link<%= " active" if request.path.to_s == "/about"%>" href="/about#">Sobre</a>
        <% if current_user %>
        <a class="nav-link" href="/users/sign_out">Sair</a>
        <% end %>
        </a>
      </nav>
    </div>
  </header>

  <%= yield %>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Feito para <a href="http://vibbra.com.br/" target="_blank">Vibbra!</a> por <a href="https://www.erija.com.br" target="_blank">Erija</a></p>
    </div>
  </footer>

  </div>
</body>

</html>

app/views/my_ratings/index.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
<%= notice %>
</div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Local</th>
      <th>Rede</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.venue.venue_name %></td>
        <td><%= render_evaluation(rating.overall_rating) %></td>
        <td><%= link_to 'Ver', "/ratings/#{rating.id}", class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Achou uma rede nova?', new_venue_path, class: "btn btn-large btn-primary" %>

app/views/venues/_form.html.erb
<%= form_with(model: venue, local: true) do |form| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="venue_name" class="col-sm-2 col-form-label">Local</label>
    <div class="col-sm-10">
      <%= form.text_field :venue_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="venue_type" class="col-sm-2 col-form-label">Tipo</label>
    <div class="col-sm-10">
      <%= form.select :venue_type, options_for_select(%w{Café Restaurante Coworking Livraria Outro}), {}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <label for="address" class="col-sm-2 col-form-label">Endereço</label>
    <div class="col-sm-10">
      <%= form.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="address" class="col-sm-2 col-form-label">Cidade</label>
    <div class="col-sm-10">
      <%= form.text_field :city, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="address" class="col-sm-2 col-form-label">País</label>
    <div class="col-sm-10">
      <%= form.text_field :country, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="network_name" class="col-sm-2 col-form-label">Rede</label>
    <div class="col-sm-10">
      <%= form.text_field :network_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="network_name" class="col-sm-2 col-form-label">Gratuita?</label>
    <div class="col-sm-10">
      <%= form.check_box :network_is_free, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="network_name" class="col-sm-2 col-form-label">Senha</label>
    <div class="col-sm-10">
      <%= form.text_field :network_password, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
  </div>

<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
<%= notice %>
</div>
<% end %>

<% if @filtered %>

<div class="row filter">

  <div class="col-sm-12">
  
    Listando por

    <% if cookies[:venue_type] && cookies[:venue_type] != "Todos" %>
    <span class="badge badge-secondary"><%= cookies[:venue_type] %></span>
    <% end %>

    <% if cookies[:price_rating] && cookies[:price_rating] != "Todos" %>
    <span class="badge badge-secondary">Preço <%= render_evaluation(cookies[:price_rating].to_i) %></span>
    <% end %>

    <% if cookies[:distance] && cookies[:distance] != "Todos" %>
    <span class="badge badge-secondary"><%= cookies[:distance] %></span>
    <% end %>

    <% unless cookies[:q].blank? %>
    <span class="badge badge-secondary">Localização <%= cookies[:q] %></span>
    <% end %>
      
  </div>
  
</div>

<% end %>

<div class="row">

<table class="table table-striped">
  <thead>
    <tr>
      <th>Estabelecimento</th>
      <th>Rede/Senha</th>
      <th>Avaliação Geral</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.venue_name %></td>
        <td><%= venue.network_name %>/<%= venue.network_password %></td>
        <td><%= render_evaluation(venue.overall_rating) %> (<%= venue.rating_count %>)  </td>
        <td><%= link_to 'Ver', venue_path(venue), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Achou uma rede nova?', new_venue_path, class: "btn btn-large btn-primary" %>

</div>

<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Buscar estabelecimentos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <div class="form-group row">
              <label for="venue_type" class="col-sm-3 col-form-label">Distância</label>
              <div class="col-sm-9">
                <select id="distance" class="form-control">
                  <%= options_for_select(%w{Todos 100m 1km 20km 100km}, cookies[:distance]) %>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label for="venue_type" class="col-sm-3 col-form-label">Tipo</label>
              <div class="col-sm-9">
                <select id="venue_type" class="form-control">
                  <%= options_for_select(%w{Todos Café Restaurante Coworking Livraria Outro}, cookies[:venue_type]) %>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label for="venue_name" class="col-sm-3 col-form-label">Localização</label>
              <div class="col-sm-9">
                <input type="text" id="q" class="form-control" value="<%= cookies[:q] %>">
              </div>
            </div>
            <div class="form-group row">
              <label for="venue_type" class="col-sm-3 col-form-label">Preço</label>
              <div class="col-sm-9">
                <select id="price_rating" class="form-control">
                  <%= options_for_select(%w{Todos 1 2 3 4 5}, cookies[:price_rating]) %>
                </select>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button id="btn-search" type="button" class="btn btn-primary">Buscar</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#btn-search-open").click(function() {
    $(".modal").modal('show');
  });

  $("#btn-search").click(function() {
    window.location.href = "/venues/save_query?distance=" + $("#distance").val() + "&q=" + $("#q").val() + "&venue_type=" + $("#venue_type").val() +  "&price_rating=" + $("#price_rating").val();
  });

</script>

app/views/venues/new.html.erb
<div class="alert alert-primary" role="alert">
  Vamos lá! Mais um local a caminho.
</div>

<%= render 'form', venue: @venue %>

app/views/venues/show.html.erb
<div class="card">
  <div class="card-body">
    <a href="/venues" type="button" class="card-close close">
      <span>&times;</span>
    </a>    

    <h5 class="card-title"><%= @venue.venue_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @venue.venue_type %></h6>

    <p class="card-text">
      <%= @venue.full_address %>

      <div class="alert alert-success" role="alert">
        REDE: <%= @venue.network_name %><br>
        SENHA: <%= @venue.network_password %>
      </div>

      <% if @venue.rating_count > 0 %>

      <div id="rating-display">

        <% if notice %>
        <div class="alert alert-info" role="alert">
        <%= notice %>
        </div>
        <% end %>

        <% unless @rating %>
        <h6>Avaliação geral</h6>
        <% else %>
        <h6>Avaliação feita em <%= @rating.created_at.strftime("%d/%m/%y às %H:%M") %></h6>
        <% end %>

        <table class="table">
          <% if @rating %>
          <tr>
            <td>Comidas</td>
            <td><%= @rating.foods %></td>
          </tr>
          <tr>
            <td>Bebidas</td>
            <td><%= @rating.drinks %></td>
          </tr>
          <% end %>
          <tr>
            <td>Atendimento</td>
            <td class="rating-large"><%= render_evaluation(@venue.service_rating) %></td>
          </tr>
          <tr>
            <td>Preço</td>
            <td class="rating-large"><%= render_evaluation(@venue.price_rating) %></td>
          </tr>
          <tr>
            <td>Conforto</td>
            <td class="rating-large"><%= render_evaluation(@venue.comfort_rating) %></td>
          </tr>
          <tr>
            <td>Nível de ruído</td>
            <td class="rating-large"><%= render_evaluation(@venue.noise_rating) %></td>
          </tr>
          <tr>
            <td>Geral</td>
            <td class="rating-large"><%= render_evaluation(@venue.overall_rating) %></td>
          </tr>        
        </table>

        <% unless @rating %>
        <a href="javascript:void(0)" class="btn btn-primary" id="rating-btn">Quero avaliar</a>
        <% end %>
        
      </div>

      <% else %>

        <div id="rating-display">

          <p>Não há avaliações desse local ainda.</p>

          <a href="javascript:void(0)" class="btn btn-primary" id="rating-btn">Quero ser o primeiro a avaliar!</a>

        </div>

      <% end %>

      <div id="rating-card" class="collapse">

        <div class="alert alert-warning" role="alert">
          Clique nas estrelas e avalie cada um dos ítens abaixo
        </div>

        <form method="post" action="/venues/<%= @venue.id %>/rate">
        <%= token_tag nil %>
        <table class="table">
          <tr>
            <td>Comidas</td>
            <td>
              <input type="text" name="rating[foods]" value="" class='form-control' placeholder="Quais tipos de comidas são servidos.">
            </td>
          </tr>
          <tr>
            <td>Bebidas</td>
            <td>
              <input type="text" name="rating[drinks]" value="" class='form-control' placeholder="Quais tipos de bebidas são servidos.">
            </td>
          </tr>
          <tr>
            <td>Atendimento</td>
            <td class="rating-large"><%= input_evaluation("rating[service_rating]") %></td>
          </tr>
          <tr>
            <td>Preço</td>
            <td class="rating-large"><%= input_evaluation("rating[price_rating]") %></td>
          </tr>
          <tr>
            <td>Conforto</td>
            <td class="rating-large"><%= input_evaluation("rating[comfort_rating]") %></td>
          </tr>
          <tr>
            <td>Nível de ruído</td>
            <td class="rating-large"><%= input_evaluation("rating[noise_rating]") %></td>
          </tr>
          <tr>
            <td>Geral</td>
            <td class="rating-large"><%= input_evaluation("rating[overall_rating]") %></td>
          </tr>        
        </table>
        <button class="btn btn-primary">Salvar</button>
        </form>
      </div>

    </p>

  </div>
</div>



<script type="text/javascript">
  
  $(".rating-star").click(function() {
    var element = $(this).data("element");
    var value = $(this).data("value");
    $("input[name=" + element.replace(/\[/, "\\[").replace(/\]/, "\\]") + "]").val(value);
    $(".rating-star").each(function() {
      if ($(this).data("element") == element) {
        if ($(this).data("value") <= value) {
          $(this).addClass("fa-star");
          $(this).removeClass("fa-star-o");
        } else {
          $(this).addClass("fa-star-o");
          $(this).removeClass("fa-star");
        }
      }
    });
  })

  $("#rating-btn").click(function() {
    $("#rating-card").show();
    $("#rating-display").hide();
  })

</script>

app/views/welcome/index.html.erb
  <main role="main" class="inner cover">
    <h1 class="cover-heading">Tá precisando conectar?.</h1>
    <p class="lead">Pesquise e compartilhe as redes que estão ao seu alcance.</p>
    <p class="lead">
      <a href="/my_ratings#" class="btn btn-lg btn-secondary">Login</a>
    </p>
  </main>